# Generated by Django 4.0.2 on 2022-03-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userlocation_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.userlocation'),
            preserve_default=False,
        ),
    ]
