# Generated by Django 4.0.2 on 2022-02-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_book_available_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_language',
            field=models.CharField(default=0, max_length=50, verbose_name='Оригинал'),
            preserve_default=False,
        ),
    ]
