# Generated by Django 4.0.2 on 2022-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vendor_code',
            field=models.IntegerField(default=0, verbose_name='Артикул'),
        ),
    ]
