# Generated by Django 4.0.2 on 2022-03-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_vendor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='vendor_code',
        ),
    ]
