# Generated by Django 4.0.2 on 2022-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
